language: go
sudo: required
dist: trusty

go:
  - 1.13.x

env:
  global:
  - PATH=$GOROOT/bin:$GOPATH/bin:$PATH
  - CGO_ENABLED=0
  matrix:
  - TARGET=amd64
  - TARGET=arm64

matrix:
  fast_finish: true
  include:
    - os: windows
      env: TARGET=amd64
      go: 1.13.x

install:
  - go get github.com/mitchellh/cli
  - go get github.com/soniah/gosnmp
  - go get github.com/go-bindata/go-bindata
  - go get github.com/smarkm/golang-underscore
 


notifications:
  email: false
